spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://eulji-room-db.c3w40a4mes94.ap-northeast-2.rds.amazonaws.com:3306/eulji_room?serverTimezone=Asia/Seoul&useSSL=false
    username: admin


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true